"""add house_address column to auth_users

Revision ID: 03713aba5cbd
Revises: e56c619c6bda
Create Date: 2026-02-05 23:05:12.173835

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



revision = '03713aba5cbd'
down_revision = 'e56c619c6bda'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_users', sa.Column('house_address', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_users', 'house_address')
    # ### end Alembic commands ###
