"""drop auth_users table

Revision ID: 80a2e256675b
Revises: 93c37ec9be91
Create Date: 2026-02-06 00:35:53.574573

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

revision = '80a2e256675b'
down_revision = '93c37ec9be91'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_users_email'), table_name='auth_users')
    op.drop_index(op.f('ix_auth_users_id'), table_name='auth_users')
    op.drop_index(op.f('ix_auth_users_username'), table_name='auth_users')
    op.drop_table('auth_users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_users',
    sa.Column('id', sa.VARCHAR(length=36), server_default=sa.text("nextval('auth_users_id_seq'::regclass)"), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('role', postgresql.ENUM('admin', 'user', name='auth_user_role'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('auth_users_pkey'))
    )
    op.create_index(op.f('ix_auth_users_username'), 'auth_users', ['username'], unique=True)
    op.create_index(op.f('ix_auth_users_id'), 'auth_users', ['id'], unique=True)
    op.create_index(op.f('ix_auth_users_email'), 'auth_users', ['email'], unique=True)
    # ### end Alembic commands ###
