"""alter auth_userd table

Revision ID: 93c37ec9be91
Revises: d20fb0d63b00
Create Date: 2026-02-05 23:54:09.445823

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



revision = '93c37ec9be91'
down_revision = 'd20fb0d63b00'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.String(length=100), nullable=False))
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=False))
    # ensure enum exists first
    op.execute("CREATE TYPE user_role AS ENUM ('admin', 'user')")
    op.add_column('users', sa.Column('role', sa.Enum('admin', 'user', name='user_role'), nullable=False))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'role')
    # drop enum type if no longer used
    op.execute("DROP TYPE IF EXISTS user_role")
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###
