"""alter auth_user table

Revision ID: d20fb0d63b00
Revises: 03713aba5cbd
Create Date: 2026-02-05 23:23:58.111989

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



revision = 'd20fb0d63b00'
down_revision = '03713aba5cbd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_users', 'phone_number')
    op.drop_column('auth_users', 'house_address')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_users', sa.Column('house_address', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('auth_users', sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
