"""add role to auth_users

Revision ID: e56c619c6bda
Revises: 0002_create_auth_users
Create Date: 2026-02-05 20:46:34.380538

"""
from __future__ import annotations
from sqlalchemy.dialects import postgresql

from alembic import op
import sqlalchemy as sa



revision = 'e56c619c6bda'
down_revision = '0002_create_auth_users'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    role_enum = postgresql.ENUM("admin", "user", name="auth_user_role")
    role_enum.create(op.get_bind(), checkfirst=True)
 
    op.add_column(
        "auth_users",
        sa.Column("role", role_enum, nullable=False, server_default="user"),
    )
    # if you don’t want the default afterwards:
    op.alter_column("auth_users", "role", server_default=None)
    op.alter_column(
        'auth_users',
        'id',
        existing_type=sa.INTEGER(),
        type_=sa.String(length=36),
        existing_nullable=False,
        postgresql_using='id::varchar',
    )
    # remove the old sequence default created by SERIAL
    op.execute("ALTER TABLE auth_users ALTER COLUMN id DROP DEFAULT")
    op.drop_index(op.f('ix_auth_users_id'), table_name='auth_users')
    op.create_index(op.f('ix_auth_users_id'), 'auth_users', ['id'], unique=True)
    op.alter_column(
        'users',
        'id',
        existing_type=sa.INTEGER(),
        type_=sa.String(length=36),
        existing_nullable=False,
        postgresql_using='id::varchar',
    )
    op.execute("ALTER TABLE users ALTER COLUMN id DROP DEFAULT")
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.alter_column('users', 'id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_auth_users_id'), table_name='auth_users')
    op.create_index(op.f('ix_auth_users_id'), 'auth_users', ['id'], unique=False)
    op.alter_column('auth_users', 'id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('auth_users', 'role')
    role_enum = postgresql.ENUM("admin", "user", name="auth_user_role")
    role_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
